name: Terraform CI/CD
permissions:
  contents: read
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan 

      - name: Checkov Scan
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .

      - name: Notify on Slack if Checkov fails
        if: failure() && steps.checkov.outcome == 'failure'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "channel": "#social",
              "text": ":x: Checkov scan failed in GitHub Actions!\n*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref }}\n*Triggered by:* @${{ github.actor }}\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Terraform Apply
        if: failure() && steps.checkov.outcome == 'passed'
        #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        #if: github.ref == 'refs/heads/main' && github.event_name == 'push' 
        run: terraform destroy -auto-approve
      
      - name: Get job status
        if: always()
        id: job_status
        uses: amannn/action-job-status@v3

      - name: Notify on Slack if job failed (but not Checkov)
        if: failure() && steps.checkov.outcome != 'failure'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "channel": "#social",
              "text": ":x: *Terraform CI/CD failed!*\n*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref }}\n*Triggered by:* @${{ github.actor }}\n*Failed step:* ${{ steps.job_status.outputs.failedStep }}\n*Error:* ${{ steps.job_status.outputs.failedStepMessage }}\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|workflow run>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify on Slack if job succeeded
        if: success()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "channel": "#social",
              "text": ":white_check_mark: *Terraform CI/CD succeeded!*\n*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref }}\n*Triggered by:* @${{ github.actor }}\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}